plugins:
  - jekyll-3rd-party-libraries
  - jekyll-archives-v2
  - jekyll-cache-bust
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-socials
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

imagemagick:
  enabled: false
